apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  labels: 
    app: petclinic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command:
          - sh
          - -c
          - |
            apk add --no-cache netcat-openbsd
            until nc -z mysql-service 3306; do
            echo "Waiting for database connection..."
            sleep 5
            done
            echo "MySQL is available"
      containers:
      - name: petclinic
        image: aravindnimmala/petclinic:V103
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: mysql
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        volumeMounts:
          - mountPath: /bindings/secret
            name: binding
            readOnly: true
      volumes:
        - name: binding
          secret:
            secretName: petclinic-binding

---
apiVersion: v1
kind: Secret
metadata:
  name: petclinic-binding
type: Opaque
stringData:
  MYSQL_URL: jdbc:mysql://mysql-service:3306/petclinic
  MYSQL_USER: petclinic
  MYSQL_PASS: petclinic
  MYSQL_ROOT_PASSWORD: root



